"""empty message

Revision ID: 1877c1017f55
Revises: a774ad9e5e92
Create Date: 2025-01-03 21:16:52.552764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1877c1017f55'
down_revision = 'a774ad9e5e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('views')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('item_tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('item_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='items_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name='items_pkey')
    )
    op.create_table('views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bookmark', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('write', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('archive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='views_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='views_pkey')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('proj_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('proj_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('project_id', name='projects_pkey')
    )
    # ### end Alembic commands ###
