"""empty message

Revision ID: a774ad9e5e92
Revises: 9ed9e705b8b1
Create Date: 2025-01-03 13:49:06.236301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a774ad9e5e92'
down_revision = '9ed9e705b8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_tag', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('item_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('item_end_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('start_date')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proj_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proj_end_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('start_date')

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookmark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('write', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archive', sa.Boolean(), nullable=True))
        batch_op.drop_column('Bookmark')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Bookmark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('archive')
        batch_op.drop_column('delete')
        batch_op.drop_column('write')
        batch_op.drop_column('read')
        batch_op.drop_column('bookmark')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('proj_end_date')
        batch_op.drop_column('proj_start_date')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('item_end_date')
        batch_op.drop_column('item_start_date')
        batch_op.drop_column('item_tag')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
