# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - application-projectplanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv env
          source env/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !env/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B73F624C5524EE99099B307AF953D4C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0647D08F5B0D4D4F92567787B7DA137D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B0771A7E7FC141EC82DF6BA7EEC52090 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'application-projectplanner'
          slot-name: 'Production'

      - name: Retrieve DATABASE_URL from Azure
        id: get-database-url
        run: |
          DATABASE_URL=$(az webapp config appsettings list --name application-projectplanner --resource-group DefaultResourceGroup-EUS --query "[?name=='DATABASE_URL'].value" -o tsv)
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

      - name: Initialize Database
        run: |
          source env/bin/activate
          python create_tables.py
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
